import typescript from '@rollup/plugin-typescript';
import replace from '@rollup/plugin-replace';
import { readFileSync } from 'node:fs';

const { version } = JSON.parse(
    readFileSync(new URL('./package.json', import.meta.url), 'utf8')
);

const banner = `//
// THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT BY HAND!
//`;

const plugins = (target) => [
    replace({ preventAssignment: true, values: { __VERSION__: version } }),
    typescript({ target, noEmitOnError: true }),
];

export default [
    {
        input: 'xiterable.ts',
        plugins: plugins('es2020'),
        output: { file: 'xiterable.js', format: 'es', banner },
    },
    {
        input: 'xiterable.ts',
        plugins: plugins('es2020'),
        output: {
            file: 'commonjs/xiterable.js',
            format: 'cjs',
            exports: 'named',
            banner,
        },
    },
    {
        input: 'xiterable.ts',
        plugins: plugins('es2020'),
        output: {
            file: 'umd/xiterable.js',
            format: 'umd',
            name: 'Xiterable',
            exports: 'named',
            banner,
        },
    },
];
